# Generated by Django 3.1.1 on 2020-09-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageindexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedvideo',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('associated_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageindexer.indexedvideo')),
            ],
        ),
    ]
